# Generated by Django 4.2.6 on 2023-10-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, default='images/placeholder.jpg', upload_to='images/'),
        ),
    ]
