# Generated by Django 4.2.6 on 2023-10-21 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character'),
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
