# Generated by Django 4.2.6 on 2023-10-21 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('base', '0002_alter_quest_character_delete_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
